cart/urls.py
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from django.urls.conf import include

from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import error404, error500

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    # <--- API --->
    path('api-auth/', include('rest_framework.urls')),

    # <--- CUSTOM APPS --->
    path('', include('clients.urls', namespace='clients')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('products.urls', namespace='products')),

    # <--- AUTH --->
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(
        template_name='auth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page="login"), name='logout'),

]

# <--- DEBUG --->
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error404
handler500 = error500

cart/models.py
from django.db import models
from products.models import Product


class Basket(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    quantity = models.PositiveIntegerField(verbose_name="Количество", default=0)
    add_datetime = models.DateTimeField(verbose_name="Время", auto_now_add=True)

    @classmethod
    def get_item(cls, pk):
        return cls.objects.filter(pk=pk).first()

orders/models.py
from django.contrib.auth.models import User

from django.db import models
from django.db.models import Count, Q

from clients.models import *
from delivery.models import *
from marketing.models import *
from products.models import *
from staff.models import *


class Order(models.Model):
    NEW = 'NEW'
    PREORDER = 'PRO'
    PREPARING = 'PRP'
    READY = 'RDY'
    DELIVERED = 'DLV'
    COMPLETED = 'COM'
    CANCELED = 'CAN'

    ORDER_STATUS_CHOICES = (
        (NEW, 'Новый'),
        (PREORDER, 'Предзаказ'),
        (PREPARING, 'Готовится'),
        (READY, 'Готов'),
        (DELIVERED, 'Доставляется'),
        (COMPLETED, 'Выполнен'),
        (CANCELED, 'Отменен')
    )

    CASH = 'CAS'
    ONLINE = 'ONL'
    TERMINAL = 'TER'
    TRANSFER = 'TRN'

    PAY_METHOD_CHOICES = (
        (CASH, 'Наличными'),
        (ONLINE, 'Онлайн'),
        (TERMINAL, 'Терминал'),
        (TRANSFER, 'Переводом')
    )

    client_data = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        verbose_name="Клиент",
        related_name="c_order",
        blank=True,
        null=True,
    )
    order_status = models.CharField(
        "Статус заказа",
        max_length=3,
        choices=ORDER_STATUS_CHOICES,
        default=NEW,
        blank=True,
        null=True,
    )
    delivery_price = models.ForeignKey(
        DeliveryPrice,
        on_delete=models.SET_NULL,
        verbose_name="Стоимость доставки",
        related_name="shipping_cost",
        blank=True,
        null=True,
    )
    discount_sum = models.ForeignKey(
        Discounts,
        on_delete=models.SET_NULL,
        verbose_name="Скидка на заказ",
        related_name="orders_discount",
        blank=True,
        null=True,
    )
    pay_method = models.CharField(
        "Способ оплаты",
        choices=PAY_METHOD_CHOICES,
        default=CASH,
        max_length=3,
        blank=True,
        null=True,
    )
    paid = models.BooleanField(verbose_name="Оплачено", default=False)
    persons = models.PositiveIntegerField("Количество персон",
                                          blank=True, null=True, default=0)
    pre_order = models.DateTimeField("Доставить", blank=True, null=True)
    staff_comment = models.TextField("Комментарий для повара",
                                     max_length=150, blank=True, null=True)
    sales_channel = models.ForeignKey(
        SalesChannel,
        on_delete=models.SET_NULL,
        verbose_name="Канал продаж",
        related_name="channels",
        blank=True,
        null=True,
    )
    courier = models.ForeignKey(
        Courier,
        on_delete=models.CASCADE,
        verbose_name="Курьер",
        related_name="courier",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField("Создано", auto_now_add=True)
    updated_at = models.DateTimeField("Обновлено", auto_now=True)
    operator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Оператор",
    )

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"
        ordering = ['-created_at']

    def __str__(self):
        return f"Заказ №{self.pk}"

    # def new_orders_count(self):
    #     return Order.objects.filter(Q(order_status="COM") |
    #                                 Q(order_status="CAN"))

    # def get_absolute_url(self):
    #     return reverse("order_detail", kwargs={'pk': self.pk})
    #
    # @cached_property
    # def is_new(self):
    #     return self.order_status == self.NEW
    #
    # @cached_property
    # def order_items(self):
    #     return self.order_items.select_related('product').all()
    #
    # @cached_property
    # def total_quantity(self):
    #     return sum(list(map(lambda x: x.quantity, self.order_items)))
    #
    # @cached_property
    # def total_cost(self):
    #     return sum(list(map(lambda x: x.quantity * x.product.price, self.order_items)))
    #
    # @property
    # def summary(self):
    #     items = self.order_items.select_related('product').all()
    #     return {
    #         "total_cost": sum(list(map(lambda x: x.quantity * x.product.price, items))),
    #         "total_quantity": sum(list(map(lambda x: x.quantity, self.order_items)))
    #     }
    #


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name="Заказ",
        blank=True,
        null=True,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='order_items',
        verbose_name="Продукт",
        blank=True,
        null=True,
    )
    quantity = models.PositiveIntegerField(
        verbose_name="Количество",
        default=1,
        blank=True,
        null=True,
    )
    price = models.PositiveIntegerField(verbose_name="Цена")

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    # @cached_property
    # def get_cost(self):
    #     return self.product.price * self.quantity
    #
    # @classmethod
    # def get_item(cls, pk):
    #     return cls.objects.filter(pk=pk).first()

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 999)]


# PRODUCT_QUANTITY_CHOICES = '1'


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from cart.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@login_required
def cart_add(request):
    product_id = request.POST.get('product')
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cleaned = form.cleaned_data
        cart.add(product=product,
                 quantity=cleaned['quantity'],
                 update_quantity=cleaned['update'])
        return HttpResponse(status=200)
    return True


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return HttpResponse(status=200)


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_section.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

templates/cart/cart_section.html
<!-- СЕКЦИЯ КОРЗИНЫ -->
<section class="col col-sm new_order_section hide_scroll">
    <div class="mt-3">
        <table>
            <tr>
                <th>Промокод:</th>
                <td>
                    <input type="text" class="form-control form-control-sm fw-bold text-center">
                </td>
            </tr>
            <tr>
                <th>Скидка:</th>
                <td>{{ form_order.discount_sum }}</td>
            </tr>
        </table>
    </div>
    <div class="scroll price_list shadow-sm mb-3 mt-3">
        <table class="table table-sm table-bordered table-striped bg-white ">
            <thead>
            <tr class="sticky-top price_list_thead">
                <th scope="col" class="text-center">#</th>
                <th scope="col">Позиций</th>
                <th scope="col" class="text-center">Кол.во</th>
                <th scope="col" class="text-center" style="width: 15%">Цена</th>
            </tr>
            </thead>
            <tbody style="font-size: 14px">
{#            {% for foo in cart %}#}
                <tr>
                    <th scope="row" class="text-center">1</th>
                    <td class="col-9 fs-6">{{ product.name }}</td>
                    <td class="text-center align-middle">
                        <div class="quantity_inner">
                            <button type="button" class="bt_minus">
                                <svg viewBox="0 0 24 24">
                                    <line x1="5" y1="12" x2="19" y2="12"></line>
                                </svg>
                            </button>
                            <input type="text" value="{{ item.quantity|default:'0' }}" class="quantity" data-max-count="999"
                                   data-id="{{ product.id }}"/>
                            <button class="bt_plus" type="button">
                                <svg viewBox="0 0 24 24">
                                    <line x1="12" y1="5" x2="12" y2="19"></line>
                                    <line x1="5" y1="12" x2="19" y2="12"></line>
                                </svg>
                            </button>
                        </div>
                    </td>
                    <td class="text-center fs-6">{{ item.total_price|default:'0' }} ₽</td>
                </tr>
{#            {% endfor %}#}

            <tr>
                <th scope="row" class="text-center">2</th>
                <td class="col-9 fs-6">Спайси-Ман (острые с говядиной)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button type="button" class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button type="button" class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">3</th>
                <td class="col-9 fs-6">Чикен-Ман (с курицей)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">999999 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">4</th>
                <td class="col-9 fs-6">Веджи-Ман (с тыквой)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">5</th>
                <td class="col-9 fs-6">Тейсти-Ман (с бараниной)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">6</th>
                <td class="col-9 fs-6">Картоф-Ман (с картофелем)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">7</th>
                <td class="col-9 fs-6">Ман-Гетсы (жареные пельмени 12 шт.)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">8</th>
                <td class="col-9 fs-6">Греческий салат (200 г.)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">9</th>
                <td class="col-9 fs-6">Свекольный салат (200 г.)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">10</th>
                <td class="col-9 fs-6">Coca-Cola Classic (500 мл)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="20"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            <tr>
                <th scope="row" class="text-center">11</th>
                <td class="col-9 fs-6">Sprite (500 мл)</td>
                <td class="text-center align-middle">
                    <div class="quantity_inner">
                        <button class="bt_minus">
                            <svg viewBox="0 0 24 24">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                        <input type="text" value="1" size="2" class="quantity" data-max-count="999"/>
                        <button class="bt_plus">
                            <svg viewBox="0 0 24 24">
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </button>
                    </div>
                </td>
                <td class="text-center fs-6">798 ₽</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div>
        <table>
            <tr>
                <th>Количество персон:</th>
                <td>{{ form_order.persons }}</td>
            </tr>
            <tr>
                <th>Стоимость доставки:</th>
                <td>{{ form_order.delivery_price }}</td>
            </tr>
            <tr>
                <th>Способ оплаты:</th>
                <td>{{ form_order.pay_method }}</td>
                <th><label for="id_paid" style="cursor: pointer">Оплачено:</label></th>
                <td>{{ form_order.paid }}</td>
            </tr>
        </table>
        <div class="mt-4 mb-3 text-center">
            {#            <h3 class="fw-bold">К оплате: 512 ₽</h3>#}
            <h4 class="fw-bold">К оплате: {{ cart.get_total_price|default:'0' }} ₽</h4>
        </div>
        <div class="text-center">
            <input type="submit" id="save-order" class="btn btn-sm btn-primary" value="Сохранить"/>
        </div>

    </div>
</section>