cart/urls.py
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from django.urls.conf import include

from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import error404, error500

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    # <--- API --->
    path('api-auth/', include('rest_framework.urls')),

    # <--- CUSTOM APPS --->
    path('', include('clients.urls', namespace='clients')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('products.urls', namespace='products')),

    # <--- AUTH --->
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(
        template_name='auth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page="login"), name='logout'),

]

# <--- DEBUG --->
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error404
handler500 = error500

orders/urls.py
from django.urls import path

from .views import *

app_name = 'orders'

urlpatterns = [
    path('', OrdersListView.as_view(), name='orders_list'),
    path('pre_orders/', PreOrdersListView.as_view(), name='pre_orders_list'),
    path('completed_orders/', CompletedOrdersListView.as_view(), name='completed_orders_list'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_detail/<int:pk>/check', CheckDetailView.as_view(), name='check'),
    path('order_detail/<int:pk>/invoice', InvoiceDetailView.as_view(), name='invoice'),

    path('dashboard/', DashBoardView.as_view(), name='dash'),

    # ________ CRUD ________
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
    path('update_order/<int:pk>/', UpdateOrderView.as_view(), name='update_order'),
]

orders/models.py
from django.contrib.auth.models import User

from django.db import models
from django.db.models import Count, Q

from clients.models import *
from delivery.models import *
from marketing.models import *
from products.models import *
from staff.models import *


class Order(models.Model):
    NEW = 'NEW'
    PREORDER = 'PRO'
    PREPARING = 'PRP'
    READY = 'RDY'
    DELIVERED = 'DLV'
    COMPLETED = 'COM'
    CANCELED = 'CAN'

    ORDER_STATUS_CHOICES = (
        (NEW, 'Новый'),
        (PREORDER, 'Предзаказ'),
        (PREPARING, 'Готовится'),
        (READY, 'Готов'),
        (DELIVERED, 'Доставляется'),
        (COMPLETED, 'Выполнен'),
        (CANCELED, 'Отменен')
    )

    CASH = 'CAS'
    ONLINE = 'ONL'
    TERMINAL = 'TER'
    TRANSFER = 'TRN'

    PAY_METHOD_CHOICES = (
        (CASH, 'Наличными'),
        (ONLINE, 'Онлайн'),
        (TERMINAL, 'Терминал'),
        (TRANSFER, 'Переводом')
    )

    client_data = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        verbose_name="Клиент",
        related_name="c_order",
        blank=True,
        null=True,
    )
    order_status = models.CharField(
        "Статус заказа",
        max_length=3,
        choices=ORDER_STATUS_CHOICES,
        default=NEW,
        blank=True,
        null=True,
    )
    delivery_price = models.ForeignKey(
        DeliveryPrice,
        on_delete=models.SET_NULL,
        verbose_name="Стоимость доставки",
        related_name="shipping_cost",
        blank=True,
        null=True,
    )
    discount_sum = models.ForeignKey(
        Discounts,
        on_delete=models.SET_NULL,
        verbose_name="Скидка на заказ",
        related_name="orders_discount",
        blank=True,
        null=True,
    )
    pay_method = models.CharField(
        "Способ оплаты",
        choices=PAY_METHOD_CHOICES,
        default=CASH,
        max_length=3,
        blank=True,
        null=True,
    )
    paid = models.BooleanField(verbose_name="Оплачено", default=False)
    persons = models.PositiveIntegerField("Количество персон",
                                          blank=True, null=True, default=0)
    pre_order = models.DateTimeField("Доставить", blank=True, null=True)
    staff_comment = models.TextField("Комментарий для повара",
                                     max_length=150, blank=True, null=True)
    sales_channel = models.ForeignKey(
        SalesChannel,
        on_delete=models.SET_NULL,
        verbose_name="Канал продаж",
        related_name="channels",
        blank=True,
        null=True,
    )
    courier = models.ForeignKey(
        Courier,
        on_delete=models.CASCADE,
        verbose_name="Курьер",
        related_name="courier",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField("Создано", auto_now_add=True)
    updated_at = models.DateTimeField("Обновлено", auto_now=True)
    operator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Оператор",
    )

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"
        ordering = ['-created_at']

    def __str__(self):
        return f"Заказ №{self.pk}"

    # def new_orders_count(self):
    #     return Order.objects.filter(Q(order_status="COM") |
    #                                 Q(order_status="CAN"))

    # def get_absolute_url(self):
    #     return reverse("order_detail", kwargs={'pk': self.pk})
    #
    # @cached_property
    # def is_new(self):
    #     return self.order_status == self.NEW
    #
    # @cached_property
    # def order_items(self):
    #     return self.order_items.select_related('product').all()
    #
    # @cached_property
    # def total_quantity(self):
    #     return sum(list(map(lambda x: x.quantity, self.order_items)))
    #
    # @cached_property
    # def total_cost(self):
    #     return sum(list(map(lambda x: x.quantity * x.product.price, self.order_items)))
    #
    # @property
    # def summary(self):
    #     items = self.order_items.select_related('product').all()
    #     return {
    #         "total_cost": sum(list(map(lambda x: x.quantity * x.product.price, items))),
    #         "total_quantity": sum(list(map(lambda x: x.quantity, self.order_items)))
    #     }
    #


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name="Заказ",
        blank=True,
        null=True,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='order_items',
        verbose_name="Продукт",
        blank=True,
        null=True,
    )
    quantity = models.PositiveIntegerField(
        verbose_name="Количество",
        default=1,
        blank=True,
        null=True,
    )
    price = models.PositiveIntegerField(verbose_name="Цена")

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    # @cached_property
    # def get_cost(self):
    #     return self.product.price * self.quantity
    #
    # @classmethod
    # def get_item(cls, pk):
    #     return cls.objects.filter(pk=pk).first()

orders/views.py
from datetime import timedelta
from pprint import pprint

from django.http import JsonResponse, HttpResponse, Http404
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from config.views import error404
from orders.forms import *

from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views import View
from django.views.generic import DetailView

from products.models import Category
from .models import Order, OrderItem


class CreateOrderView(LoginRequiredMixin, View):
    """Форма создания заказа"""

    raise_exception = True

    def get(self, request, *args, **kwargs):
        order = Order.objects.all()
        new_order_pk = order.first()
        if new_order_pk is None:
            new_order_pk = 'Заказ №1'
        else:
            new_order_pk = f'Заказ №{order.first().id + 1}'

        context = {
            'categories': Category.objects.filter(available=True),
            'form_client': ClientForm,
            'form_order': OrderForm,
            'new_order_num': new_order_pk,
            'title': "Новый заказ"
        }
        return render(request, 'orders/new_order.html', context)

    def post(self, request):
        form_client = ClientForm(request.POST)
        form_order = OrderForm(request.POST)
        pprint(request.POST)
        if form_client.is_valid() and form_order.is_valid():
            # Валидация формы клиента и заказа
            client_instance = form_client.save(commit=False)
            # Экземпляр клиента
            update_values = {
                'name': form_client.cleaned_data['name'],
                'address': form_client.cleaned_data['address'],
                'home': form_client.cleaned_data['home'],
                'building': form_client.cleaned_data['building'],
                'room': form_client.cleaned_data['room'],
                'entrance': form_client.cleaned_data['entrance'],
                'floor': form_client.cleaned_data['floor'],
                'code': form_client.cleaned_data['code'],
                'mark': form_client.cleaned_data['mark'],
            }
            # Словарь данных из формы
            update_client, created = Client.objects.update_or_create(
                phone=client_instance.phone,
                defaults=update_values
            )
            # Создать или обновить данные клиента
            if created:
                print(f"Клиент {update_client} создан ")
            else:
                print(f"Данные {update_client} обновлены")
            # Показать статус добавления клиента в запросах
            update_client.save()
            # Сохраняем клиента перед сохранением заказа, для передачи заказу id клиента
            client_pk = Client.objects.get(phone=client_instance.phone).id
            # Возвращаем из БД "ID" клиента
            order_instance = form_order.save(commit=False)
            # Экземпляр заказа
            order_instance.operator = request.user
            # # Сохраняем в экземпляр оператора создавшего заказ
            order_instance.client_data_id = client_pk
            # Присваиваем клиенту заказ по client_id
            form_order.save()
            # Сохраняем заказа
        return redirect('orders:orders_list')


class UpdateOrderView(LoginRequiredMixin, View):
    redirect_to_login = True

    def get(self, request, pk, *args, **kwargs):
        order = get_object_or_404(Order, id=pk)
        count_orders = Order.objects.filter(client_data__phone=order.client_data.phone).count()

        context = {
            'categories': Category.objects.filter(available=True),
            'form_client': ClientForm(instance=order.client_data),
            'form_order': OrderForm(instance=order),
            'order': order,
            'count_orders': count_orders,
            'saved_order_num': f'Заказ №{pk}',
            'title': "Изменить заказ"
        }
        return render(request, 'orders/order_update.html', context)

    def post(self, request, pk, *args, **kwargs):
        order = get_object_or_404(Order, id=pk)
        form_client = ClientForm(request.POST)
        form_order = OrderForm(request.POST, instance=order)
        pprint(request.POST)
        if form_client.is_valid() and form_order.is_valid():
            # Валидация формы клиента и заказа
            client_instance = form_client.save(commit=False)
            # Экземпляр клиента
            update_values = {
                'name': form_client.cleaned_data['name'],
                'address': form_client.cleaned_data['address'],
                'home': form_client.cleaned_data['home'],
                'building': form_client.cleaned_data['building'],
                'room': form_client.cleaned_data['room'],
                'entrance': form_client.cleaned_data['entrance'],
                'floor': form_client.cleaned_data['floor'],
                'code': form_client.cleaned_data['code'],
                'mark': form_client.cleaned_data['mark'],
            }
            # Словарь данных из формы
            update_client, created = Client.objects.update_or_create(
                phone=client_instance.phone,
                defaults=update_values
            )
            # Создать или обновить данные клиента
            if created:
                print(f"Клиент {update_client} создан ")
            else:
                print(f"Данные {update_client} обновлены")
            # Показать статус добавления клиента в запросах
            update_client.save()
            # Сохраняем клиента перед сохранением заказа, для передачи заказу id клиента
            client_pk = Client.objects.get(phone=client_instance.phone).id
            # Возвращаем из БД "ID" клиента
            order_instance = form_order.save(commit=True)
            # Экземпляр заказа
            order_instance.operator = request.user
            # Сохраняем в экземпляр оператора изменившего заказ
            order_instance.client_data_id = client_pk
            # Присваиваем клиенту заказ по client_id
            form_order.save()
            # Сохраняем заказа
        return redirect('orders:orders_list')


class OrdersListView(LoginRequiredMixin, View):
    """Список заказов в работе"""

    redirect_to_login = True

    def get(self, request, *args, **kwargs):
        orders = Order.objects.exclude(
            Q(pre_order__gt=timezone.now() + timedelta(hours=2)) |
            Q(order_status="COM") |
            Q(order_status="CAN")
        )
        # Вывести все заказы и предзаказы за 2 часа до доставки
        return render(request, 'orders/orders_list.html', context={
            'orders': orders,
            'form_status': OrderCourierForm(),
            'title': "Заказы"
        })

    def post(self, request, *args, **kwargs):
        order_id = request.POST.get('order_id')
        updated_order_status = request.POST.get('order_status')
        # updated_order_courier = request.POST.get('order_courier')
        print(request.POST)
        order = Order.objects.get(id=order_id)
        order.order_status = updated_order_status
        # order.courier_id = updated_order_courier
        order.save()
        return HttpResponse(status=200)


class PreOrdersListView(LoginRequiredMixin, View):
    """Список предзаказов"""

    redirect_to_login = True

    def get(self, request, *args, **kwargs):
        current_time = timezone.localtime()
        before_time_preparing = current_time + timedelta(hours=2)
        pre_orders = Order.objects.filter(
            Q(pre_order__gt=before_time_preparing)
        )
        # Перенести в предзаказы, время до доставки более 2х часов
        for item in pre_orders:
            if item.pre_order > before_time_preparing:
                pre_orders.update(order_status="PRO")
            # elif item.pre_order.exclude(Q(order_status="PRO") |
            #                             item.pre_order > before_time_preparing):
            # pre_orders.update(order_status='')
        # Поменять статус заказа на предзаказ

        return render(request, 'orders/pre_orders_list.html', context={
            'pre_orders': pre_orders,
            'form_status': OrderCourierForm(),
            'title': "Предзаказы"
        })


class CompletedOrdersListView(LoginRequiredMixin, View):
    """Список завершенных заказов"""

    redirect_to_login = True

    def get(self, request, *args, **kwargs):
        completed_orders = Order.objects.filter(Q(order_status="COM") |
                                                Q(order_status="CAN"))
        # Фильтровать отмененные и завершенные заказы
        return render(request, 'orders/complete_orders_list.html', context={
            'completed_orders': completed_orders,
            'form_status': OrderCourierForm(),
            'title': "Завершенные"
        })


class OrderDetailView(LoginRequiredMixin, DetailView):
    """Детали заказа"""

    model = Order
    extra_context = {'title': "Детали заказа"}
    redirect_to_login = True
    success_url = reverse_lazy('order_detail')


class CheckDetailView(LoginRequiredMixin, DetailView):
    """Чек"""

    model = Order
    template_name = 'orders/invoice/check.html'
    extra_context = {'title': "Печать чека"}
    redirect_to_login = True
    success_url = reverse_lazy('check')


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    """Накладная"""

    model = Order
    template_name = 'orders/invoice/invoice.html'
    extra_context = {'title': "Накладная"}
    redirect_to_login = True
    success_url = reverse_lazy('invoice')


class DashBoardView(LoginRequiredMixin, View):
    """"Дашборд"""

    redirect_to_login = True

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            now = timezone.now()

            orders_in_progress = Order.objects.filter(Q(order_status='NEW') |
                                                      Q(order_status='PRP') |

templates/orders/includes/navbar.html
<nav class="container-fluid shadow-sm bg-white sticky-top rounded" style="z-index: 1999">
    <div class="col-7 p-2" id="orders_nav">
        {#        {% if not user.is_superuser %}#}
        <a href="{% url "orders:create_order" %}"
           class="btn btn-sm btn-primary nav_button">+ НОВЫЙ
        </a>
        <a href="{% url "orders:orders_list" %}"
           class="btn btn-sm btn-info nav_button">
            В РАБОТЕ
        </a>
        <a href="{% url "orders:pre_orders_list" %}"
           class="btn btn-sm btn-warning nav_button">

            ПРЕДЗАКАЗЫ
        </a>
        <a href="{% url "orders:completed_orders_list" %}"
           class="btn btn-sm btn-success active nav_button">
            ЗАВЕРШЕНО
        </a>
        {#        {% endif %}#}
        {#        <button type="button" class="btn btn-sm btn-secondary nav_button">КАЛЕНДАРЬ</button>#}
    </div>
    <div class="col-5" style="text-align: right;">
        {% if user.is_superuser %}
            <a href="{% url "orders:dash" %}" class="btn btn-sm btn-dark nav_button">ДАШБОРД</a>
            <a href="{% url "admin:index" %}" class="btn btn-sm btn-dark nav_button">Админ</a>
        {% endif %}
        <a href="{% url "logout" %}" class="btn btn-sm p-1" style="width: 9rem">
            <div class="alert-info p-1 rounded-2">{{ user }}</div>
            <div>Выйти</div>
        </a>
    </div>
</nav>

templates/orders/includes/order.html
<div class="shadow-sm mb-2">
    <table class="table table-bordered mb-1 mt-1" style="background-color: #eaf7ff; border-color: steelblue">
        <tr class="text-center" style="vertical-align: middle;">


            <form method="post">
                {% csrf_token %}
                <th scope="col" class="col-1" style="width: 5%">{{ order.pk }}</th>
                <th scope="col"
                    class="col-1 {{ order.order_status }}-order"
                    id="status_data">
                    {% if order.order_status == 'COM' %}
                        <select name="order_status"
                                class="form-select fw-bold"
                                id="id_order_status"
                                data-order-id="{{ order.pk }}">
                        <option value="COM" selected>Выполнен</option>
                        <option value="CAN">Отмена</option>
                    {% elif order.order_status == 'CAN' %}
                        <select name="order_status"
                                class="form-select fw-bold"
                                id="id_order_status"
                                data-order-id="{{ order.pk }}">
                            <option value="COM">Выполнен</option>
                            <option value="CAN" selected>Отменен</option>
                        </select>
                    {% else %}
                        <select name="order_status"
                                class="form-select fw-bold"
                                id="id_order_status"
                                data-order-id="{{ order.pk }}">

                            {% if order.order_status == "NEW" %}
                                <option value="NEW" selected>Новый</option>
                            {% endif %}


                            {% if order.order_status == "PRO" %}
                                <option value="PRO" selected>Предзаказ</option>
                            {% endif %}

                            {% if order.order_status == "PRP" %}
                                <option value="PRP" selected>Готовится</option>
                            {% else %}
                                <option value="PRP">Готовится</option>
                            {% endif %}

                            {% if order.order_status == "RDY" %}
                                <option value="RDY" selected>Готов</option>
                            {% else %}
                                <option value="RDY">Готов</option>
                            {% endif %}

                            {% if order.order_status == "DLV" %}
                                <option value="DLV" selected>Доставляется</option>
                            {% else %}
                                <option value="DLV">Доставляется</option>
                            {% endif %}
                            <option value="COM">Выполнен</option>
                            <option value="CAN">Отменен</option>
                        </select>
                    {% endif %}
                </th>

                <td class="col-1">
                    <table class="m-auto">
                        <tbody>
                        <tr>
                            <td class="">
                                <table>
                                    <tbody>
                                    <tr>
                                        <td>
                                            {{ order.created_at|time:'H:i' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            {{ order.updated_at|date:'d.m' }}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td class="ps-4 pe-0">
                                <table>
                                    <tbody>
                                    <tr>
                                        <td style="color: blue">
                                            {{ order.pre_order|time:'H:i'|default:'-------' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="color: blue">
                                            {{ order.pre_order|date:'d.m'|default:'-------' }}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
                <th scope="col" class="col-2 text-start">
                    {{ order.client_data.address|default_if_none:'' }}
                    {% if  order.client_data.home != None %}
                        {{ order.client_data.home }},
                    {% else %}
                        {{ order.client_data.home|default_if_none:'' }}
                    {% endif %}

                    {% if  order.client_data.building != None %}
                        корп {{ order.client_data.building }},
                    {% else %}
                        {{ order.client_data.building|default_if_none:'' }}
                    {% endif %}

                    {% if  order.client_data.entrance != None %}
                        подъезд {{ order.client_data.entrance }},
                    {% else %}
                        {{ order.client_data.entrance|default_if_none:'' }}
                    {% endif %}

                    {% if  order.client_data.floor != None %}
                        этаж {{ order.client_data.floor }},
                    {% else %}
                        {{ order.client_data.floor|default_if_none:'' }}
                    {% endif %}

                    {% if  order.client_data.room != None %}
                        кв {{ order.client_data.room|default_if_none:'' }}
                    {% endif %}
                </th>
                <th scope="col" class="col-1">
                    <span>{{ order.client_data.name.title|default_if_none:'' }}</span><br>
                    <span id="id_phone_for_status">{{ order.client_data.phone|default_if_none:'' }}</span>
                </th>
                {% if order.paid == True %}
                    <th scope="col" class="col-1 fs-3" style="background-color: limegreen">1616 ₽</th>
                {% else %}
                    <th scope="col" class="col-1 fs-3" style="background-color: indianred">1616 ₽</th>
                {% endif %}

                <th scope="col" class="col-1">{{ form_status.courier }}</th>
                <th scope="col" class="col-1">{{ order.operator.first_name|default:order.operator }}</th>
            </form>
        </tr>
    </table>
    <div class="text-end mb-2 mt-2">

        <a href="{% url 'orders:update_order' order.pk %}"
           style="text-decoration: none"
           class="btn btn-sm btn-warning">Редактировать
        </a>

        <a href="{% url 'orders:check' order.pk %}"
           target="_blank"
           class="btn btn-sm btn-info text-decoration-none">
            Печать чека
        </a>
        <a href="{% url 'orders:invoice' order.pk %}"
           target="_blank"
           class="btn btn-sm btn-secondary text-decoration-none">
            Накладная
        </a>
    </div>
</div>

templates/orders/includes/orders_table_description.html
{% load static %}


<section class="container-fluid" style="position: sticky;top: 69px;z-index: 1;">
    <div class="m-1 bg-white shadow" style="padding-right: 12px;padding-left: 12px;margin-top: 0 !important;">
        <table class="table table-bordered mb-1 mt-1" style="background-color: darkgray">
            <tr class="text-center">
                <th scope="col" class="col-1" style="width: 5%">№ заказа</th>
                <th scope="col" class="col-1">Статус заказа</th>
                <th scope="col" class="col-1">Оформлен</th>
                <th scope="col" class="col-2">Адрес</th>
                <th scope="col" class="col-1">Имя/тел</th>
                <th scope="col" class="col-1">Сумма</th>
                <th scope="col" class="col-1">Курьер</th>
                <th scope="col" class="col-1">Оператор</th>
            </tr>
        </table>
    </div>
</section>